script: rake ci
cache: bundler
language: ruby
rvm:
- rbx
- jruby-1.7.25
- 2.2
- rbx-2
- jruby-9.1.2.0
- 2.1
- 2.3
- ruby-head
- jruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: rbx-2
  - rvm: jruby-9.1.2.0
  - rvm: 2.1
  - rvm: 2.3
  - rvm: ruby-head
  - rvm: jruby-head
env:
  global:
  - NUMBER_OF_PROCESSORS=4 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
  - CELLULOID_BACKPORTED=false
notifications:
  irc: irc.freenode.org#celluloid
  slack:
    secure: uJ8uoiNgiEDoRewbH6gj9mphUGVDtjXeEy8++vSTQkLqIkkoZ3M+mr0yldL2/ECaG8wHLH2035DHM4d54GyeVEU/8UG80UVAnYTctlzzjn1rfXPfCIsZDXYMUjXe3wvOouN+b4hjiyXe7ZsssdRoeKw6rHIU8/tUHgC3IfZel7s=
sudo: false
install: bundle install --without=development
